### ISSUE TITLE
Creating a Facility

### ISSUE THREAD

**Issue by FuadCd** [CMPUT301F24nocode/nocode-events#49]

**Comment by FuadCd** [comment]
Created a facility to with Facility name and facility description.

**Comment by ashra1-ai** [comment]
### User Story: Facility Creation
### As an organizer, I want to create a new facility with a name and description so that it can be available as a location option for events.

### Acceptance Criteria:

- Facility Creation Form
   - The facility creation page displays fields for entering a facility name and description.
   - A save button is available to submit the form.
   - Input Validation
   
- Both the name and description fields are required.
- If either field is empty, the app displays a warning message: "Please fill in all fields", and the form cannot be submitted.
- Successful Creation

- After filling in both fields, clicking Save creates the facility.
- The newly created facility is saved to Firestore and is added to the list of available facilities.
- Feedback on Submission
- On successful save, the app displays a success message, and the user is redirected back to the facility list.

If there is an error during saving, the app displays an error message allowing the organizer to retry.
